name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -f pom.xml clean compile

    - name: Run Tests with Maven
      run: |
        echo "Running tests from unusual directory structure"
        mvn -f pom.xml test -Dtest=com.devops.test.ContactFormTest
