name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 24
      uses: actions/setup-java@v2
      with:
        java-version: '24.0.1'  # Set to Java 24.0.1 instead of Java 11

    - name: Build with Maven
      run: mvn clean install
