name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Choose the operating system for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out the code from the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use the version required for your project

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y maven  # Replace with the dependencies required for your project

    - name: Run Tests
      run: |
        mvn test  # Replace this with the command to run your tests (e.g., npm test for JavaScript projects)
