name: CI Pipeline

on:
  push:
    branches:
      - main  # triggers the pipeline when code is pushed to the main branch
  pull_request:
    branches:
      - main  # triggers on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # runs the job on the latest version of Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (or the required language environment)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # specify the version of Node.js you are using

      - name: Install dependencies
        run: npm install  # for Node.js, replace with the appropriate command for your tech stack

      - name: Run tests
        run: npm test  # run tests in your project

      - name: Build Docker image
        run: docker build -t your-docker-image-name .  # replace with your Docker image name

      - name: Push Docker image to Docker Hub (optional)
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push your-docker-image-name
